# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L-OCkAEn_9VYHA7_biUadBJzb244i5wg
"""

#Take the string input and print the number of occurances of each character
st=input("enter the string ")
for i in range(len(st)):
    if len(st) == 0:
      break;
    ch = st[0]
    if ch == ' ' or ch == '\t':
      continue
    print(ch + " - ", st.count(ch))
    st = st.replace(ch, '').strip()